org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
org.gradle.caching=false
android.useAndroidX=true
android.enableJetifier=true

# 禁用所有代理
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=
systemProp.socksProxyHost=
systemProp.socksProxyPort=
systemProp.https.protocols=TLSv1.2,TLSv1.3
